name: Simple Go CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Build app
        run: go build -o app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: app

  download:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-app

      - name: Check file
        run: ls -l app