name: Go Build

on:
  push:
    branches:
      - blaze-feature

jobs:
  setup_the_build_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

  build_the_application:
    runs-on: ubuntu-latest
    needs: setup_the_build_environment

    steps:
      - name: Build Application
        run: go build -o devscale-socialmedia .

  upload_build_artifact:
    runs-on: ubuntu-latest
    needs: build_the_application

    steps:
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: devscale-socialmedia
          path: devscale-socialmedia

  download_build_artifact:
    runs-on: ubuntu-latest
    needs: upload_build_artifact

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v7
        with:
          name: devscale-socialmedia
          path: . 

  confirm_downloaded_artifiact:
    runs-on: ubuntu-latest
    needs: download_build_artifact
    steps:

      - name: List Downloaded Files
        run: ls -l devscale-socialmedia
